# Exploratory Data Analysis

## Import Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

## Loading the Dataset

In [4]:
file_path = '../Data/Product Flags/cust_info_prod_202403_processed.parquet'
march_2024 = pd.read_parquet(file_path)
march_2024

Collecting pyarrow
  Downloading pyarrow-17.0.0-cp310-cp310-macosx_10_15_x86_64.whl (29.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.0/29.0 MB 13.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.16.6 in /Users/benjaminang/anaconda3/lib/python3.10/site-packages (from pyarrow) (1.23.5)
Installing collected packages: pyarrow
Successfully installed pyarrow-17.0.0

,CUST_NUM,IB,BUILDUP_F,CASH_MANAGEMENT,CORPORATE_LOANS,RETAIL_LOAN,TRADE_SERVICES,INVESTMENT_FUNDS,SECURITIES,INSURANCE,CORPORATE_FINANCE,FOREX,REMITTANCE,CORPORATE_CARDS,BB,DEPOSITS,RETAIL_PRODUCTS,INVESTMENTS_AND_SECURITIES
0,1357.977909,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
1,1437.499217,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
2,1606.444521,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
3,2522.626409,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
4,3201.700173,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298163,13943.279528,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298164,13976.468939,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298165,14002.523487,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298166,14037.928765,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298167,14092.261139,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:


# Assuming 'march_2024' is your DataFrame, and it includes only product-related columns.
# Select only the product usage columns (exclude CUST_NUM or any other non-relevant columns)
product_columns = ['CASH_MANAGEMENT', 'CORPORATE_LOANS', 'RETAIL_LOAN', 'TRADE_SERVICES', 
                   'INVESTMENT_FUNDS', 'SECURITIES', 'INSURANCE', 'CORPORATE_FINANCE', 
                   'FOREX', 'REMITTANCE', 'CORPORATE_CARDS', 'DEPOSITS', 
                   'RETAIL_PRODUCTS', 'INVESTMENTS_AND_SECURITIES']

# Filter the dataset to only include these columns
product_data = march_2024[product_columns]

# Normalize the data (optional, if needed) to scale product usage between 0 and 1
# product_data = product_data / product_data.max()

### Step 2: Calculate Cosine Similarity ###
# Calculate the cosine similarity between customers
similarity_matrix = cosine_similarity(product_data)

# Convert the similarity matrix to a DataFrame for better readability
similarity_df = pd.DataFrame(similarity_matrix, index=march_2024['CUST_NUM'], columns=march_2024['CUST_NUM'])

# Display the similarity matrix
similarity_df.head()