# Exploratory Data Analysis

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Loading the Dataset

In [5]:
file_path = '../Data/Product Flags/cust_info_prod_202403_processed.parquet'
march_2024 = pd.read_parquet(file_path)
march_2024

,CUST_NUM,IB,BUILDUP_F,CASH_MANAGEMENT,CORPORATE_LOANS,RETAIL_LOAN,TRADE_SERVICES,INVESTMENT_FUNDS,SECURITIES,INSURANCE,CORPORATE_FINANCE,FOREX,REMITTANCE,CORPORATE_CARDS,BB,DEPOSITS,RETAIL_PRODUCTS,INVESTMENTS_AND_SECURITIES
0,1357.977909,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
1,1437.499217,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
2,1606.444521,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
3,2522.626409,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
4,3201.700173,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298163,13943.279528,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298164,13976.468939,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298165,14002.523487,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298166,14037.928765,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
298167,14092.261139,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [8]:
march_2024.columns

Index(['CUST_NUM', 'IB', 'BUILDUP_F', 'CASH_MANAGEMENT', 'CORPORATE_LOANS',
       'RETAIL_LOAN', 'TRADE_SERVICES', 'INVESTMENT_FUNDS', 'SECURITIES',
       'INSURANCE', 'CORPORATE_FINANCE', 'FOREX', 'REMITTANCE',
       'CORPORATE_CARDS', 'BB', 'DEPOSITS', 'RETAIL_PRODUCTS',
       'INVESTMENTS_AND_SECURITIES'],
      dtype='object')